### ISSUE TITLE
Files older than 1 hour are moved to table stage

### ISSUE THREAD

**Issue by ilkinulas** [snowflakedb/snowflake-kafka-connector#172]
Hi

Snowpipe sometimes hangs and can not ingest files for more than 1 hour. (Number of pending files increases) In this case snowflake-kafka-connector moves these files to table stage and when snowpipe resumes it can not find the files that are moved to table stage resulting in "LOAD_FAILED" status.

Here's the code block that moves files to table stage.
https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java#L569

Do you think that increasing the "one hour limit" is a good idea? Does it have any side effects that I can not think of at the moment?

Thank you.

**Comment by sfc-gh-zli** [comment]
If we increase the "one hour limit" to one day, we have to increase the load history check https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java#L583  from one hour to one day as well. This readOneHourHistory function is heavily throttled. If we change that to readOneDayHistory, it's going to be throttled more. 

One hour loading time should already be a .999 percentile for ingestion. It should be very rare to see files getting moved to table stage because of ingestion time-out. Even if that happened, a copy command would load the file on table stage into the table very easily.

**Comment by ilkinulas** [comment]
Thanks a lot for the explanation.

**Comment by abhishekkh** [comment]
@sfc-gh-zli @sfc-gh-japatel We are seeing these errors more frequently since Thanksgiving incident 2021 where snowpipe fails and files are moved to table stage. Even the [incident](https://status.snowflake.com/incidents/bjf9c3h843kx) yesterday lasted for 3 hours. Can we change this 1 hour window to a day now? I have opened a snowflake ticket (00457173) for this and it was closed without any action.

**Comment by sfc-gh-wfateem** [comment]
Hi @abhishekkh,
Hope you're staying warm in Austin.
This whole mechanism is going to change significantly with Snowpipe streaming. Please have a look at @sfc-gh-japatel's presentation [here](https://www.confluent.io/events/current-2022/how-snowflake-sink-connector-uses-snowpipes-streaming-ingestion-feature/) which discussed the difference between the two designs.
With respect to your concern, that 1-hour window is already very generous, and extending that to 24 hours would just introduce other challenges. For starters, the Kafka connector will have to keep track of files in memory for an entire day, but it's also going to constantly query Snowpipe asking it for historical data that goes back 24 hours, which is excessive. 
What you're describing should not be a commonly recurring issue. If that's not your experience and you're still seeing this problem even outside of reported incidents, then you have a unique case that needs to be looked at.

**Comment by abhishekkh** [comment]
@sfc-gh-wfateem Thanks for checking in, its definitely warming up here but we are still dealing with `oakacalypse`, many oak tree branches and limbs couldnt bear the weight of the ice and were dismembered.

We use a managed snowflake connector in confluent cloud. Are there any timelines when Snowpipe streaming will be enabled there? If 24 hours is a large window can we start with something smaller like 6 until then. The recent incidents have lasted for at least 2-3 hours, the one before thanksgiving and the latest one few days ago. The impact is we have 10k files sitting in table stages that we now have to run a script to ingest into the tables. This additionla step also adds latency to our data pipelines.

**Comment by sfc-gh-wfateem** [comment]
Hi @abhishekkh
Glad all is well. I'm also located in Austin by the way 😃 

As my colleagues mentioned [here](https://github.com/snowflakedb/snowflake-kafka-connector/issues/172#issuecomment-644324699), there's a significant cost to making the change you're requesting. The benefit, if it would even result in that (possible throttling), doesn't outweigh the cost. It's unfortunate that you ran into the problems you mentioned, but one hour is already very lenient. Think of it as us saying "we expect this data to be loaded within an hour."
The expectation is that it should be much sooner than that. If manual work is the concern, then I would say the better solution is to find a creative way to automate the process of detecting files in the table's stage and loading them.

**Comment by sfc-gh-japatel** [comment]
@abhishekkh we hear your valid concern and as earlier mentioned in the thread, increasing 1 hour window to 3 hours wont help. What are we doing to address this?
1. We are making sure that our Snowpipe service is more resilient. 
2. We will come up with some guidelines on how you can add monitoring on top of table stages with a recent announcement of alerts. 
Stay tuned!
