### ISSUE TITLE
Snowflake Connector doesn't allow role to be specified while making connection

### ISSUE THREAD

**Issue by saggarsunil** [snowflakedb/snowflake-kafka-connector#200]
Version - 1.4.1

In snowflake, a user can have multiple roles. 
Current connector version doesn't allow us to specify the role which should be used while making snowflake connection.

It ignores, the unspecified keys. I think we should give a generic way of specifying the parameters to connector. Something like 

SNOWFLAKE_{Actual_snowflake_property_name}

**Comment by sfc-gh-zli** [comment]
Kafka Connector use the default role of the user.

**Comment by adisunw** [comment]
Why does the connector only allow for use of the default role for the user though? As @saggarsunil mentioned, users can utilize multiple roles, so shouldn't the connector have config capabilities to allow for this?

**Comment by sfc-gh-japatel** [comment]
We have this capability for snowpipe streaming. Please try it out in version 1.9.4

**Comment by adisunw** [comment]
I saw that, however the role isn't actually be used in the connector https://github.com/snowflakedb/snowflake-kafka-connector/issues/571.

I'm using version 1.9.3, and I see the `snowflake.role.name` config introduced in 1.9.1 https://github.com/snowflakedb/snowflake-kafka-connector/issues/571

**Comment by sfc-gh-japatel** [comment]
Yes we used the role only for snowpipe streaming. check this out: https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka

In version 1.9.4 we use that role which is being uniformly used along with JDBC connection

**Comment by adisunw** [comment]
Sounds good, thanks! This should resolve role issues for any connectors utilizing snowpipe streaming as an ingestion method, but is there any reason why this `snowflake.role.name` wasn't rolled out to snowpipe ingestion as well? 

I ask because i'de like to use some of the Snowflake converters, but these are not supported when snowpipe streaming is used https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka#converters

**Comment by sfc-gh-japatel** [comment]
I understand you would want to use snowpipe because thats still GA, but we want our customers to slowly migrate to snowpipe streaming as there are certain benefits: 
1. lower latency
2. lower cost (In most of the cases)
3. Better error handling
4. The snowflake converters are not manageable and there are better community converters - that is the reason we dont support it in our snowpipe streaming ingestion mode. Any reason why you would want to stick to snowflake converters? (apart from snowpipe and table stage error handling)

**Comment by adisunw** [comment]
We have a number of older connectors that I am trying to transition to snowpipe streaming, but unfortunately the community converters are not quite to parity of the snowflake converters.

For example, the `org.apache.kafka.connect.json.JsonConverter` outputs data as a varchar whereas the `com.snowflake.kafka.connector.records.SnowflakeJsonConverter` outputs data as a true variant. This results in downstream jobs that query these tables to first cast the data via `parse_json`. 

also thank you for being so quick in your responses!

**Comment by sfc-gh-japatel** [comment]
@adisunw ahh I see the issue. thanks for explanation. 

We dont have plans to support SnowflakeConverters because
1. It cant support SMT. 
2. Sends data to Table stage instead of DLQ and hence customers will not be able to monitor. DLQ is defacto way to handle errors in kafka and we would like everyone to keep using it. 
3. Community converters are constantly getting evolved and maintained by large number of contributors. 

We have schematization available for snowpipe streaming, can that be of any use to you so that you dont have to parse json after it lands in snowflake? https://docs.snowflake.com/release-notes/2023-07#schema-detection-and-evolution-for-kafka-connector-with-snowpipe-streaming-preview
