### ISSUE TITLE
There is no way to trigger flush in the connector without writing a record

### ISSUE THREAD

**Issue by dlg99** [snowflakedb/snowflake-kafka-connector#444]
Looking at SnowflakeSinkServiceV1:

https://github.com/snowflakedb/snowflake-kafka-connector/blob/ed1b37a3554be84892e99e165023d0b856ecd24f/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java#L144-L147

the only time so-called "timed flush" is called only on the record insert.
This not the behavior one expects if e.g. a burst of writes is followed by a long period of inactivity. In that case last unflushed data won't be flushed

ScheduledExecutorService can be an easy solution for this.

Adding the ScheduledExecutorService externally, in a wrapper around the connector, does not work because preCommit does not call flush.

**Comment by sfc-gh-rcheng** [comment]
We have taken a background flush service as a feature request, however do not have any guarantees due to other priorities. Alternatively you may use the Kafka max.poll.interval.ms property to periodically poll and flush the buffer. This is set to a default 5 minutes by Kafka.

Closing this issue out due to age - please reopen if further discussion is needed.

**Comment by sfc-gh-wfateem** [comment]
@sfc-gh-rcheng I'm reopening this because it's something I have noticed in recent tests I was performing. I'll try to look into this.

**Comment by sfc-gh-gjachimko** [comment]
is there anything extra to add to this ticket from your side @sfc-gh-wfateem ? it's been sitting idle for quite some time, can we assume it is resolved by now?

**Comment by sfc-gh-wfateem** [comment]
@sfc-gh-gjachimko I didn't get around to it because it's not an issue for Snowpipe streaming, which is now the common and recommended setup. I don't know if it makes much sense to invest any time looking into this.

With that said, I'll go ahead and close the issue. If anyone has any reason for not being able to use Snowpipe Streaming as the ingestion method and is impacted by this problem, please reopen this issue and we'll pick this up again.
