### ISSUE TITLE
Kafka connector params does not take effect when using 1.8.2 snowflake-kafka-connector + snowpipe streaming

### ISSUE THREAD

**Issue by hbpeng0115** [snowflakedb/snowflake-kafka-connector#557]
Hello, we are using 1.8.2 snowflake-kafka-connector + snowpipe streaming to load Kafka data to snowflake table. However, we found some common Kafka connector params does not take effect when post json to connector.
`client.id = xxx,
auto.offset.reset = latest`
So we want to know how to set offset and client id in snowflake-kafka-connector?

**Comment by sfc-gh-japatel** [comment]
this properties can be set at a connector level and not at snowflake connector level. can you try it while you are starting your connect runttime?

**Comment by HuiboPeng** [comment]
Hello, I understand we can set in the connector level. But if we want to set different offset property in different topics in one group of Kafka connector, we can not set in the connector level, but need to set it connector level.

**Comment by sfc-gh-japatel** [comment]
I see, that makes sense. Can you send some logs on what you are seeing when you set this at snowflake connector level?

**Comment by HuiboPeng** [comment]
I checked the log, but there is no warning/error logs. It seems SNFL connector can not parse the parameter _**auto.offset.reset,**_ so just use the default value.

**Comment by sfc-gh-japatel** [comment]
Yeah, we dont have special handling of these configs. But in general, Snowflake KC should start ingesting from whatever the latest offset is.

**Comment by HuiboPeng** [comment]
Hi, @sfc-gh-japatel Does Snowflake side want to handle this issue? Because it's difficult for us to deploy multi number connectors with different offset setting.

**Comment by sfc-gh-japatel** [comment]
Hi, we will take this as a feature request.

**Comment by sfc-gh-japatel** [comment]
Just trying to understand the usecase, would you mind describing your case to us? This will help us prioritize. 

Thanks

**Comment by sfc-gh-wfateem** [comment]
@hbpeng0115 going to close this off because our understanding of your issue is that this is something you can address by overriding your Kafka Connect worker's configurations starting with Kafka 2.3. If that's not working as expected then that would be considered more of a Kafka issue rather than a sink connector (Snowflake Kafka Connector) issue. If you still have any questions or still need more assistance then please feel free to reopen the issue and I'll be happy to work with you to help figure out what's going on.
