### ISSUE TITLE
Empty partitions and "Offset Token not present"

### ISSUE THREAD

**Issue by JonathonO** [snowflakedb/snowflake-kafka-connector#636]
Hi @sfc-gh-tzhang and co, it seems like empty partitions are causing an issue. 

We're getting "Offset Token not present" log spam [fetchLatestCommittedOffsetFromSnowflake](https://github.com/snowflakedb/snowflake-kafka-connector/blob/f8da3c59ece4c00f59f1276f07d0e9816d03745c/src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java#L956) and have done since v1.9.1. In the last 24 hours we upgraded to v1.9.3 and it's the same (except the log level's elevated to warning since v1.9.2).

We've looked at the Consumer Groups, Topics and Partitions for a dozen or so of the logs and they were all empty partitions, either empty from the time the topic was first created, or, messages have all expired for that partition.

Is there some action we should take to resolve these or is it bug?

There's something else that seems like an issue for empty partitions due to message expiration: let's say the low/high watermarks or log end offset is 11,000. Messages 0. For some reason, the Consumer Group offset is also showing 0?

Is the Sink adjusting or resetting the offset in certain scenarios? I know offset handling has changed since v1.9.1.

**Comment by sfc-gh-tzhang** [comment]
@JonathonO To confirm, are you saying that there're more `OffsetToken not present` message after switching to 1.9.2? I agree that we should probably keep it as INFO, but the number of messages should be same as 1.9.1, otherwise it might be an indication that something is causing the channel to be invalidated. 

> There's something else that seems like an issue for empty partitions due to message expiration: let's say the low/high watermarks or log end offset is 11,000. Messages 0. For some reason, the Consumer Group offset is also showing 0?

Not sure if I understand your question, could you elaborate?

**Comment by JonathonO** [comment]
Hi @sfc-gh-tzhang, thanks for getting back to me 👍 

> @JonathonO To confirm, are you saying that there're more `OffsetToken not present` message after switching to 1.9.2? I agree that we should probably keep it as INFO, but the number of messages should be same as 1.9.1, otherwise it might be an indication that something is causing the channel to be invalidated.

No, on average the number of messages are the same between the two versions, but it's **constant**, and seems to be related to empty partitions.

> > There's something else that seems like an issue for empty partitions due to message expiration: let's say the low/high watermarks or log end offset is 11,000. Messages 0. For some reason, the Consumer Group offset is also showing 0?
> 
> Not sure if I understand your question, could you elaborate?

Of course!

Using that example, it seems like the Consumer Group offset has been reset to 0. 

The topic partition's log end offset is 11,000, meaning at least 11k messages have passed through that partition at some point but have since expired because of topic retention settings.

Assuming the Sink is consuming records successfully and at a rate that prevents messages expiring before being consumed, shouldn't the Consumer Group offset be 11,000 not 0?

The Snowflake Sink does manage offsets to some degree. For 1.9.1 at least, we had seen Snowflake Sink log messages saying `Reset kafka offsets to: ...`, so we assume they're related. It's not something we've seen with other non-Snowflake Consumers, however they'll be relying more on [Kafka Consumer offset management](https://docs.confluent.io/platform/current/clients/consumer.html#id1) so possibly not a valid assumption to make?

**Comment by sfc-gh-tzhang** [comment]
The consumer group offset shouldn't be reset to 0, it should be reset to the offset token stored at server side in order to guarantee exactly once delivery, we have a SHOW CHANNELS command you can use to check the offset token for each channel. We can't simply rely on the Kafka offset management since it's not exactly once. Please take a look at https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka#exactly-once-semantics.

For verifying whether there is any missing rows, you can check the number of rows in table with the offset info in the RECORD_METADTA column

**Comment by sfc-gh-tzhang** [comment]
Closing now, feel free to reopen or create a new one if needed
