### ISSUE TITLE
Different offset behaviour between SNOWPIPE & SNOWPIPE_STREAMING

### ISSUE THREAD

**Issue by simonepm** [snowflakedb/snowflake-kafka-connector#690]
Hello,

we are using Snowflake Kafka Connector 2.0.0 SNOWPIPE_STREAMING, but noticed the same also on previous versions.

We set up the connector properties as follows:

SnowflakeSinkConnectorConfig.BUFFER_SIZE_BYTES, SnowflakeSinkConnectorConfig.BUFFER_SIZE_BYTES_MIN
SnowflakeSinkConnectorConfig.BUFFER_COUNT_RECORDS, SnowflakeSinkConnectorConfig.BUFFER_COUNT_RECORDS_MIN
SnowflakeSinkConnectorConfig.BUFFER_FLUSH_TIME_SEC, SnowflakeSinkConnectorConfig.BUFFER_FLUSH_TIME_SEC_MIN
SnowflakeSinkConnectorConfig.BEHAVIOR_ON_NULL_VALUES_CONFIG, "IGNORE"

When we perform a load of records on Kafka, the first time the Sink connector behaves correctly; on subsequent load of the same records - no records is load into Snowflake, despite the re-loaded records being present on Kafka itself.

If we perform the same operation with SNOWPIPE everything works correctly, so we suspect the issue is with how the CHANNELS offset is managed. Furthermore, if we DROP and CREATE the SINK table again, the message lands.

We replicated the test on local environment doing the following, twice, toward the same Snowflake table and instance:

- spin up a Kafka instance
- send 1 message (**same message value and key**)
- wait for the message to land on Snowflake
- tear down everything

The first time, the message lands - the second (and subsequent) does not. The only thing changed is an increase of the client_sequencer by one, while row_sequencer and offset_token stay at 0.

- Is there a way to reset a CHANNEL?
- Is there a way to let SNOWPIPE_STREAMING read new records like SNOWPIPE do?
- How SNOWPIPE_STREAMING decide that a message should not be sent again on Snowflake? Is this based on the Kafka key?

Following the log comparison between the 2 runs:

### First run:

```
INFO org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=test-sink-connector-0} Executing sink task
DEBUG org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=test-sink-connector-0} Partitions assigned [<topic>-0]
DEBUG org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=test-sink-connector-0} Assigned topic partition <topic>-0 with offset 0
DEBUG com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1 - [SF_KAFKA_CONNECTOR] table <table>_600570976 doesn't exist
INFO com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2 - [SF_KAFKA_CONNECTOR] Creating new table <table>_<hash>.
INFO com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1 - [SF_KAFKA_CONNECTOR] create table <table>_<hash>
INFO com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Opening a channel with name:<topic>_0 for table name:<table>_<hash>
DEBUG com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Fetching last committed offset for partition channel:<namespace>.<table>_<hash>.<topic>_0
INFO com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Fetched offsetToken for channelName:<namespace>.<table>_<hash>.<topic>_0, offset:null
INFO com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] TopicPartitionChannel:<namespace>.<table>_<hash>.<topic>_0, offset token is NULL, will rely on Kafka to send us the correct offset instead
INFO com.snowflake.kafka.connector.SnowflakeSinkTask - [SF_KAFKA_CONNECTOR] task opened with 1 partitions, execution time: 717 milliseconds
DEBUG com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Flush based on buffered bytes or buffered number of records for channel:<namespace>.<table>_<hash>.<topic>_0,currentBufferSizeInBytes:16789, currentBufferedRecordCount:1, connectorBufferThresholds:StreamingBufferThreshold{bufferFlushTimeThreshold=10, bufferByteSizeThreshold=1, bufferRecordCountThreshold=1}
DEBUG com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Invoking insertRows API for channel:<namespace>.<table>_<hash>.<topic>_0, streamingBuffer:StreamingBuffer{numOfRecords=1, bufferSizeBytes=16789, firstOffset=0, lastOffset=0}
DEBUG com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Get rows for streaming ingest. 1 records, 16789 bytes, offset 0 - 0
INFO com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Successfully called insertRows for channel:<namespace>.<table>_<hash>.<topic>_0, buffer:StreamingBuffer{numOfRecords=1, bufferSizeBytes=16789, firstOffset=0, lastOffset=0}, insertResponseHasErrors:false, needToResetOffset:false
DEBUG com.snowflake.kafka.connector.SnowflakeSinkTask - [SF_KAFKA_CONNECTOR] Successfully called PUT with 1 records, executionTime: 49 ms
```

### Second run:

```
INFO org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=test-sink-connector-0} Executing sink task
DEBUG org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=test-sink-connector-0} Partitions assigned [<topic>-0]
DEBUG org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=test-sink-connector-0} Assigned topic partition <topic>-0 with offset 0
INFO com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2 - [SF_KAFKA_CONNECTOR] Using existing table <table>_<hash>.
INFO com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Opening a channel with name:<topic>_0 for table name:<table>_<hash>
DEBUG com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Fetching last committed offset for partition channel:<namespace>.<table>_<hash>.<topic>_0
INFO com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel - [SF_KAFKA_CONNECTOR] Fetched offsetToken for channelName:<namespace>.<table>_<hash>.<topic>_0, offset:0
DEBUG org.apache.kafka.connect.runtime.WorkerSinkTaskContext - WorkerSinkTaskContext{id=test-sink-connector-0} Setting offset for topic partition <topic>-0 to 1
INFO com.snowflake.kafka.connector.SnowflakeSinkTask - [SF_KAFKA_CONNECTOR] task opened with 1 partitions, execution time: 567 milliseconds
```

Many thanks!

**Comment by sfc-gh-japatel** [comment]
Is there a way to reset a CHANNEL?
- Yes, you can use reset channel, we will publish docs soon. 
Is there a way to let SNOWPIPE_STREAMING read new records like SNOWPIPE do?
- Ideally you dont need to do anything, it should pick up the new message. It is possible, it is inside the buffer. 
How SNOWPIPE_STREAMING decide that a message should not be sent again on Snowflake? Is this based on the Kafka key?
- Snowflake kafka connector calls the insertRows API when it hits one of the thresholds you described. 


Can I ask what is the poll interval ms property?

**Comment by simonepm** [comment]
Sure, thanks!

At the moment everything is on default Kafka values, so 5 minutes.

The strange thing is that the same config works smoothly with SNOWPIPE, the second message lands immediately - but not with SNOWPIPE_STREAMING.

I am trying reducing poll interval, but I suspect the issue is 'something else' due to the fact that by dropping the table, the message lands like if it is the first time, despite the max poll interval value.

**Comment by simonepm** [comment]
Yes, can confirm this behavior 100%.

In the end we can conclude that the difference between SNOWPIPE and SNOWPIPE_STREAMING is intended and in order to re-load the data we have 2 choices:
- "drop and recreate the table until we make it possible for you to reset the offset in a given channel"
- "you can use reset channel, we will publish docs soon"

Many thanks for the clarifications! I would close the issue if you agree.

**Comment by sfc-gh-xhuang** [comment]
Here is the function doc link to update offsets for a channel: https://docs.snowflake.com/en/sql-reference/functions/system_snowpipe_streaming_update_channel_offset_token

**Comment by ebuildy** [comment]
We have 1200 partitions / channels, is it possible to make it programmatically?  

I dont understand why the kafka connector dont loop polling until channel offset  = consumer offset + 1.

<img width="794" alt="Capture d’écran, le 2024-05-13 à 20 17 18" src="https://github.com/snowflakedb/snowflake-kafka-connector/assets/1219817/ad167a31-9643-44cb-a24a-774dc12ec491">

**Comment by sfc-gh-wfateem** [comment]
Hi @ebuildy,

If your offset in Snowflake is higher than your consumer's committed offset in Kafka, then it means you recreated that topic and produced messages again.

Now, what's unclear from your description is whether or not you actually have messages in your partition leading up to the offset in Snowflake. For instance, in your fourth row, do you actually have offsets 64717 to 129434 in the partition? If so, then once you send offset 129435 to Snowflake you can expect your consumer group's committed offset to advance to 129435 after we commit that. Everything else lower than 129434 is ignored because we treat that as duplicate data. In this scenario, it's actually in your best interest to reset the offset because having the connector simply "loop" through the data means you're going to lose those messages since we're treating those as duplicates.

If you don't actually have that data then the Snowflake Kafka Connector can't really do anything about that. We instruct Kafka to start consuming from offset 129434 + 1 (i.e. start one message after the last one we saw and committed), and since that doesn't exist in your partition you'll see some error about an invalid offset thrown by Kafka. That's just going to continue until you eventually produce enough data to the partition to bring this back into a valid state. 

You might want to open a new issue in case you have a unique situation outside of what I have described and walk us through that scenario step by step.

**Comment by ebuildy** [comment]
You are right, we have re-created our consumer and removed `connect-consumer-offsets` topic. My expectation was the client will consume messages for nothing until it matches snowflake offsets.

(I recreated it because sometime I am in this opposite situation where kafka consumer is > snowflake offset:)

<img width="1351" alt="Capture d’écran, le 2024-05-14 à 07 51 49" src="https://github.com/snowflakedb/snowflake-kafka-connector/assets/1219817/a84b3be6-4dd3-472e-b415-ed7a73ccb5f6">

Nothing happen, in our case, I am pretty sure this is because we have too many topics/partitions (1200 !), but we are working on sizing (btw any doc/best practice will be appreciated).

So when I run the Kafka Connector with less topics (simply set `topicsRegex: "^bi_ing_9_petalmd_absence(.*)$"`), this is working fine except for partitions where kafka consumer is ahead of snowflake offset, I had to reset consumer offset manually:

```sh
./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group connect-snowflake-connector-v2 --topic bi_ing_9_petalmd_absence_limits --reset-offsets --to-earliest --execute
```

I hope this not happen too much, or do you know a way to make it programmatically?

Thanks you, this plugin is really nice!

**Comment by sfc-gh-wfateem** [comment]
Hey @ebuildy,

I think I understand where the confusion is coming from. What you're showing in that screenshot is actually an okay state to be in. In Kafka, your offsets start from 0, and the current offset just means the consumer's current position that it will start consuming from. For example, if you create a brand new topic with a single partition and send 3 messages, then your partition is going to have messages with offsets 0, 1, and 2. However, when you run your consumer group command in Kafka it will show you that the committed offset (or current offset) is 3, and the log end offset is 3. In reality, you don't have a message with offset 3, but if you then send 100 messages, the consumer will begin fetching messages starting with offset 3, which is what we want to happen.

Now, on the Snowflake's side, going back to the state where you only had 3 messages. We're only showing you the last message we _saw_ and _committed_ to the table. That's the very last message with offset 2. When you restart the connector and Kafka Connect starts our tasks, we ask Kafka to begin consuming from our offset (offset token) + 1, and that should _**always**_ be smaller or equal to the consumer group's committed (current offset) in Kafka.

**Comment by ebuildy** [comment]
yeah it makes sense! Thanks you for such detailed answer.

I am starting to understand how connector work, we have lot of trouble with consumer partitions rebalances:
 
<img width="963" alt="Capture d’écran, le 2024-05-15 à 14 30 14" src="https://github.com/snowflakedb/snowflake-kafka-connector/assets/1219817/0f242d68-d073-4ac9-86fe-ad5ae3835e87">

Here some kafka connect tasks receive too many partitions, Snowflake connector tries to open lot of channels, this take lof of time and resource and it seems crash, hence kafka kill consumer group members and this loop:

<img width="748" alt="Capture d’écran, le 2024-05-15 à 14 31 05" src="https://github.com/snowflakedb/snowflake-kafka-connector/assets/1219817/578da952-d008-4b7b-9108-f976bb5386a1">

up -> tries to open channels -> crash -> rebalance -> up -> crash

I dont know if the issue is from Kafka <-> Kafka Connect or Snowflake side :-/ 

Maybe the connector should open channels in a lazy fashion when it receives message for?

**Comment by sfc-gh-wfateem** [comment]
It does get a bit complicated to figure out who's responsible for what when our connector is heavily dependent on Kafka Connect. They both share some responsibilities, so the rebalancing could be anything. If there's an issue with the connector causing tasks to fail, then that would trigger your rebalances. 

The partition assignment to the tasks is purely Kafka's responsibility, so if you're suspecting that's the issue and you believe balancing that out a bit more would help then my suggestion is that you try setting the following configuration:
`consumer.override.partition.assignment.strategy=CooperativeStickyAssignor` 

However, you need to be sure your Kafka environment is at a version that includes this fix:
https://issues.apache.org/jira/browse/KAFKA-12487

Otherwise, try:
`consumer.override.partition.assignment.strategy= StickyAssignor` 

If you still have any issues with this and you think there's something on the Kafka Connector side that can be looked at, then do you think you can create a separate issue? The discussion here is starting to deviate from the original problem so it can get a bit confusing for others to follow.

**Comment by ebuildy** [comment]
Well I dont know, I see lot of WARN logs because snowflake channels is invalited, offsets not good etc... and this make the kafka connect kick out from cluster, then kafka rebalance partitions then the crash loop :-/ 

We use already StickAssignor:

```
    consumer.max.poll.interval.ms: 600000
    consumer.max.poll.records: 100
    consumer.partition.assignment.strategy: org.apache.kafka.clients.consumer.StickyAssignor
    consumer.request.timeout.ms: 60000
    consumer.session.timeout.ms: 40000
```

**Comment by sfc-gh-japatel** [comment]
@ebuildy 
We have few improvements coming up in later version of connector where we will close channels parallely. 
May be we should also try to open channels parallely if there are so many partitions per channel. 

one other observation is using sticky assignor as your kafka partition strategy is helpful when you have a lot of partitions per topic.

**Comment by ebuildy** [comment]
> @ebuildy We have few improvements coming up in later version of connector where we will close channels parallely. May be we should also try to open channels parallely if there are so many partitions per channel.
> 
> one other observation is using sticky assignor as your kafka partition strategy is helpful when you have a lot of partitions per topic.
> 
> #841

Ho yeah!

Our use case is 400 topics for 1200 partitions in total. I think this is too many, sometimes kafka gives 1000 partitions for a single task :-/
