### ISSUE TITLE
Enhancement Request: Publish committed offsets in a clean & configurable way

### ISSUE THREAD

**Issue by joepardi** [snowflakedb/snowflake-kafka-connector#96]
I would like to submit an enhancement request to publish committed offsets to a designated topic in Kafka, whereby a microservice could listen for and process them shortly after the records were committed to Snowflake.  Some background info in Stackoverflow can be found here:
[https://stackoverflow.com/questions/59758541/writing-records-into-snowflake-from-kafka/59808570#59808570](https://stackoverflow.com/questions/59758541/writing-records-into-snowflake-from-kafka/59808570#59808570)

The wrapped technique suggested in Stackoverflow can work but support directly within the connector would be more appropriate.

**Comment by sfc-gh-zli** [comment]
I want to give some background about how offset commitment works in Kafka Connector. For all versions previous to v1.4.0, we commit offset to Kafka Connect only after we see the records in Snowflake table. Since v1.4.0, we commit offset immediately after we call "ingest api". There is a delay between calling ingest api and records showing up in table. So there could be cases when you see a record is committed but it didn't show up in Snowflake table.
